[package]
name = "blockchain_tutorial"
version = "0.1.0"
authors = ["Masayuki Sunahara <tamanishi@gmail.com>"]

[dependencies]
serde = "1.0.30"
serde_json = "1.0.11"
serde_derive = "1.0.30"
time = "0.1.39"
rust-crypto = "0.2.36"
